"""update

Revision ID: 42f464647a3a
Revises: 2c4d3851de7b
Create Date: 2023-07-16 19:37:14.077594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42f464647a3a'
down_revision = '2c4d3851de7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
