"""update

Revision ID: b2ff19a6ada3
Revises: ebf2637b2902
Create Date: 2023-07-16 19:27:07.861520

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b2ff19a6ada3"
down_revision = "ebf2637b2902"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
