"""update

Revision ID: ebf2637b2902
Revises: 8bc61624c0fc
Create Date: 2023-07-16 19:11:25.132660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebf2637b2902'
down_revision = '8bc61624c0fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('accounts_customer_id_fkey', 'accounts', type_='foreignkey')
    op.create_foreign_key(None, 'accounts', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.create_foreign_key('accounts_customer_id_fkey', 'accounts', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###
